//! MangaYomi JavaScript extension runtime.

pub mod bridge;
pub mod crypto;

use std::collections::HashMap;
use std::sync::mpsc::{channel, Receiver, Sender};
use std::sync::{Arc, Mutex};
use std::thread::JoinHandle;
use std::time::{Duration, Instant};

use anyhow::{anyhow, bail, Context as _, Result};
use rquickjs::{Context, Ctx, Exception, Function, Promise, Runtime, Value as JsValue};
use serde_json::Value as JsonValue;

use crate::settings::SourceSettingValue;
use crate::source::mangayomi::html::MangaYomiDom;
use crate::source::mangayomi::js::bridge::{host_send_message, install, JsBridge};

/// How long a single extension method call may run before it is aborted.
pub const DEFAULT_INVOKE_TIMEOUT: Duration = Duration::from_secs(60);

/// Grace period given to the interrupt handler to abort the running script
/// before the caller gives up on the reply channel.
const INTERRUPT_LEEWAY: Duration = Duration::from_secs(2);

/// The JS bridge polyfill (Client, Document, Element, SharedPreferences,
/// MProvider skeleton, String/crypto helpers, `jsonStringify`). Generated by
/// bun from the TypeScript sources in `polyfill/` (see `build.rs`).
pub(crate) const POLYFILL_JS: &str = include_str!("../js_assets/polyfill.js");

/// Request sent to the worker thread. `args` is a JSON array serialising
/// the positional arguments of the method call.
struct WorkerRequest {
    method: String,
    args: String,
    reply: Sender<Result<String>>,
}

/// Runs one MangaYomi JavaScript extension. All calls are synchronous from
/// the outside; each one blocks until the runtime produces the result.
pub struct MangayomiJsRuntime {
    code: String,
    metadata: JsonValue,
    prefs: Arc<Mutex<HashMap<String, SourceSettingValue>>>,
    timeout: Duration,
    worker: Mutex<Option<WorkerHandle>>,
}

struct WorkerHandle {
    tx: Sender<WorkerRequest>,
    thread: JoinHandle<()>,
}

impl MangayomiJsRuntime {
    pub fn new(
        code: String,
        metadata: JsonValue,
        prefs: Arc<Mutex<HashMap<String, SourceSettingValue>>>,
        timeout: Duration,
    ) -> Result<Self> {
        let runtime = Self {
            code,
            metadata,
            prefs,
            timeout,
            worker: Mutex::new(None),
        };
        runtime.start_worker()?;
        Ok(runtime)
    }

    /// Calls a method of the provider instance (`getPopular`, `getDetail`,
    /// `getPageList`, `getSourcePreferences`, `getHeaders`, `supportsLatest`,
    /// ...) and returns the JSON value produced by the runtime.
    pub fn invoke(&self, method: &str, args: Vec<JsonValue>) -> Result<JsonValue> {
        let mut attempts = 0;
        loop {
            let reply_rx = {
                let mut worker = self.worker.lock().unwrap();
                let needs_restart = worker
                    .as_ref()
                    .map(|w| w.thread.is_finished())
                    .unwrap_or(true);
                if needs_restart {
                    *worker = None;
                    drop(worker);
                    self.start_worker()?;
                    continue;
                }
                let (reply_tx, reply_rx) = channel();
                worker
                    .as_ref()
                    .unwrap()
                    .tx
                    .send(WorkerRequest {
                        method: method.to_string(),
                        args: serde_json::to_string(&args).unwrap_or_else(|_| "[]".to_string()),
                        reply: reply_tx,
                    })
                    .context("failed to send request to extension worker")?;
                reply_rx
            };

            match reply_rx.recv_timeout(self.timeout) {
                Ok(result) => {
                    let json = result?;
                    return serde_json::from_str(&json).context("extension returned invalid JSON");
                }
                Err(_) => {
                    log::warn!(
                        "MangaYomi JS extension call `{}` timed out; restarting the runtime",
                        method
                    );
                    let mut worker = self.worker.lock().unwrap();
                    *worker = None;
                    attempts += 1;
                    if attempts >= 2 {
                        bail!("extension call `{}` timed out twice", method);
                    }
                }
            }
        }
    }

    fn start_worker(&self) -> Result<()> {
        let code = self.code.clone();
        let metadata = self.metadata.clone();
        let prefs = self.prefs.clone();
        let timeout = self.timeout;

        let (tx, rx) = channel();
        let thread = std::thread::Builder::new()
            .name("mangayomi-js-worker".to_string())
            .spawn(move || {
                worker_main(rx, &code, &metadata, prefs, timeout);
            })
            .context("failed to spawn MangaYomi JS extension worker thread")?;
        *self.worker.lock().unwrap() = Some(WorkerHandle { tx, thread });
        Ok(())
    }
}

fn worker_main(
    rx: Receiver<WorkerRequest>,
    code: &str,
    metadata: &JsonValue,
    prefs: Arc<Mutex<HashMap<String, SourceSettingValue>>>,
    timeout: Duration,
) {
    if let Err(err) = worker_loop(rx, code, metadata, prefs, timeout) {
        log::warn!("MangaYomi JS extension worker exited: {:#}", err);
    }
}

/// Builds the `MSource` JSON object the `MProvider.source` getter returns,
/// from the stored `index.json` entry. Mirrors `MSource.toJson()` in the
/// app (`eval/model/m_source.dart`).
fn msource_json(metadata: &JsonValue) -> JsonValue {
    let mut out = serde_json::Map::new();
    for key in [
        "id",
        "name",
        "lang",
        "baseUrl",
        "apiUrl",
        "dateFormat",
        "dateFormatLocale",
        "additionalParams",
        "notes",
        "isFullData",
        "hasCloudflare",
    ] {
        out.insert(
            key.to_string(),
            metadata.get(key).cloned().unwrap_or(JsonValue::Null),
        );
    }
    JsonValue::Object(out)
}

fn worker_loop(
    rx: Receiver<WorkerRequest>,
    code: &str,
    metadata: &JsonValue,
    prefs: Arc<Mutex<HashMap<String, SourceSettingValue>>>,
    timeout: Duration,
) -> Result<()> {
    let runtime = Runtime::new().context("failed to create QuickJS runtime")?;
    let interrupt_deadline: Arc<Mutex<Option<Instant>>> = Arc::new(Mutex::new(None));
    {
        let deadline = interrupt_deadline.clone();
        runtime.set_interrupt_handler(Some(Box::new(move || {
            matches!(
                *deadline.lock().unwrap(),
                Some(d) if Instant::now() >= d
            )
        })));
    }

    let source_json = msource_json(metadata);

    let context = Context::full(&runtime).context("failed to create QuickJS context")?;
    match context.with(|ctx| {
        let client = crate::tls::blocking_client_builder()
            .timeout(Duration::from_secs(60))
            .build()
            .context("failed to build HTTP client for MangaYomi JS worker")?;
        install(JsBridge {
            client,
            dom: MangaYomiDom::new(),
            elements: HashMap::new(),
            next_key: 0,
            prefs: prefs.clone(),
        });
        register_globals(&ctx, &source_json, code)
    }) {
        Ok(()) => {}
        Err(err) => {
            eprintln!("[mangayomi-js] worker init failed: {:#}", err);
            return Err(err);
        }
    }
    log::debug!("MangaYomi JS extension worker started");

    while let Ok(request) = rx.recv() {
        let result = context.with(|ctx| {
            let deadline = if timeout > INTERRUPT_LEEWAY {
                timeout - INTERRUPT_LEEWAY
            } else {
                timeout
            };
            *interrupt_deadline.lock().unwrap() = Some(Instant::now() + deadline);
            let result = invoke_method(&ctx, &request.method, &request.args, &source_json);
            *interrupt_deadline.lock().unwrap() = None;
            result
        });
        if request.reply.send(result).is_err() {
            // The caller gave up (timeout); stop the worker so a stuck
            // script does not linger.
            break;
        }
    }
    Ok(())
}

fn register_globals(ctx: &Ctx<'_>, source_json: &JsonValue, code: &str) -> Result<()> {
    let globals = ctx.globals();
    globals.set("sendMessage", Function::new(ctx.clone(), host_send_message))?;

    let source_literal =
        serde_json::to_string(source_json).context("failed to serialise MSource")?;
    eval_script(
        ctx,
        "MSource bootstrap",
        &format!("var RAKUYOMI_SOURCE = {source_literal};"),
    )?;

    eval_script(ctx, "polyfill.js", POLYFILL_JS)?;

    eval_script(ctx, "extension code", code)?;

    // Same tail as the app's `JsExtensionService._init()`.
    eval_script(
        ctx,
        "DefaultExtension instantiation",
        "var extention = new DefaultExtension();",
    )?;
    Ok(())
}

/// Evaluates `script`, tagging failures with the script name.
fn eval_script(ctx: &Ctx<'_>, label: &str, script: &str) -> Result<()> {
    ctx.eval::<(), _>(script)
        .map_err(|e| anyhow!("failed to evaluate {label}: {} ({})", e, label))
}

/// The methods the app invokes through the async path
/// (`jsonStringify(() => extention.method(...))`); everything else is
/// invoked synchronously.
fn is_async_method(method: &str) -> bool {
    matches!(
        method,
        "getPopular"
            | "getLatestUpdates"
            | "search"
            | "getDetail"
            | "getPageList"
            | "getVideoList"
            | "getHtmlContent"
            | "cleanHtmlContent"
    )
}

/// Builds the JS expression for `extention.<call>` the way the app does
/// (`getHeaders(url)` for `headers`, the bare getter for `supportsLatest`).
/// Normalised `getFilterList()` output for `search`, mirroring the app: the
/// raw extension filter list is passed through, with `state` defaults the
/// app's `*.fromJson` round-trip would have applied (select/tri-state -> 0,
/// checkbox -> false, recursing into group children). Extensions may omit
/// `state` where the app would supply it (e.g. Mangafire's "Length" filter).
const SEARCH_FILTER_LIST_EXPR: &str = r#"(function () {
  function d(f) {
    if (!f || typeof f !== "object") return f;
    var t = f.type_name || "";
    if (f.state === undefined) {
      if (t.indexOf("TriState") >= 0 || t.indexOf("Select") >= 0 || Array.isArray(f.values)) {
        f.state = 0;
      } else {
        f.state = false;
      }
    }
    if (Array.isArray(f.state)) {
      for (var i = 0; i < f.state.length; i++) f.state[i] = d(f.state[i]);
    }
    return f;
  }
  try {
    var fl = extention.getFilterList();
    return Array.isArray(fl) ? fl.map(d) : fl;
  } catch (e) {
    return [];
  }
})()"#;

fn call_expr(method: &str, args: &[JsonValue], source_json: &JsonValue) -> String {
    let base_url = source_json
        .get("baseUrl")
        .and_then(JsonValue::as_str)
        .unwrap_or_default();
    match method {
        "supportsLatest" => "extention.supportsLatest".to_string(),
        "headers" => format!(
            "extention.getHeaders({})",
            serde_json::to_string(base_url).unwrap_or_else(|_| "\"\"".to_string())
        ),
        _ => {
            let mut args_js: Vec<String> = args
                .iter()
                .map(|a| serde_json::to_string(a).unwrap_or_else(|_| "null".to_string()))
                .collect();
            // The app hands the extension its true filter list on search, not
            // an empty one: extensions that index `filters[0].state`
            // unconditionally (e.g. Mangafire) crash on a plain `[]`. See
            // `SEARCH_FILTER_LIST_EXPR`.
            if method == "search" && args_js.len() == 3 {
                args_js[2] = SEARCH_FILTER_LIST_EXPR.to_string();
            }
            format!("extention.{}({})", method, args_js.join(", "))
        }
    }
}

fn invoke_method(
    ctx: &Ctx<'_>,
    method: &str,
    args_json: &str,
    source_json: &JsonValue,
) -> Result<String> {
    let args: Vec<JsonValue> = serde_json::from_str(args_json).unwrap_or_default();
    let call = call_expr(method, &args, source_json);

    if is_async_method(method) {
        let script = format!("jsonStringify(() => {call})");
        let value: JsValue<'_> = ctx
            .eval(script)
            .context("failed to evaluate extension call")?;
        let promise =
            Promise::from_value(value).context("extension call did not return a promise")?;
        // `finish` drives the QuickJS job queue until the promise settles.
        // All host functions are synchronous, so it always settles here.
        match promise.finish::<String>() {
            Ok(value) => Ok(value),
            Err(e) => bail!(
                "extension method `{}` failed: {}",
                method,
                js_error_detail(ctx, e)
            ),
        }
    } else {
        let script = format!("JSON.stringify({call})");
        match ctx.eval::<String, _>(script) {
            Ok(value) => Ok(value),
            Err(e) => bail!(
                "extension method `{}` failed: {}",
                method,
                js_error_detail(ctx, e)
            ),
        }
    }
}

/// Formats a caught QuickJS exception as `message\nstack` (stack omitted
/// when empty), falling back to the raw rquickjs error.
fn js_error_detail(ctx: &Ctx<'_>, e: rquickjs::Error) -> String {
    let value = ctx.catch();
    value
        .as_object()
        .and_then(|obj| Exception::from_object(obj.clone()))
        .map(|ex| {
            let message = ex.message().unwrap_or_default();
            let stack = ex.stack().unwrap_or_default();
            if stack.trim().is_empty() {
                message
            } else {
                format!("{message}\n{stack}")
            }
        })
        .unwrap_or_else(|| format!("{:#}", e))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn metadata() -> JsonValue {
        json!({
            "id": 524070078,
            "name": "Asura Scans",
            "lang": "en",
            "baseUrl": "https://asurascans.com",
            "apiUrl": "https://api.asurascans.com",
            "version": "0.2.14",
            "sourceCodeLanguage": 1,
        })
    }

    #[test]
    fn test_msource_json_keys() {
        let json = msource_json(&metadata());
        assert_eq!(json["baseUrl"], "https://asurascans.com");
        assert_eq!(json["apiUrl"], "https://api.asurascans.com");
        assert_eq!(json["id"], 524070078);
        assert_eq!(json["lang"], "en");
        assert!(json["dateFormat"].is_null());
        assert!(json["hasCloudflare"].is_null());
    }

    #[test]
    fn test_call_expr() {
        let source = msource_json(&metadata());
        assert_eq!(
            call_expr("headers", &[], &source),
            "extention.getHeaders(\"https://asurascans.com\")"
        );
        assert_eq!(
            call_expr("supportsLatest", &[], &source),
            "extention.supportsLatest"
        );
        assert_eq!(
            call_expr("getPopular", &[json!(1)], &source),
            "extention.getPopular(1)"
        );
        assert_eq!(
            call_expr(
                "search",
                &[json!("one piece"), json!(1), json!([])],
                &source
            ),
            format!("extention.search(\"one piece\", 1, {SEARCH_FILTER_LIST_EXPR})")
        );
    }

    #[test]
    fn test_is_async_method() {
        assert!(is_async_method("getPopular"));
        assert!(is_async_method("getDetail"));
        assert!(!is_async_method("supportsLatest"));
        assert!(!is_async_method("getSourcePreferences"));
    }
}
