include!("src/settings/schema.rs");

use schemars::schema_for;
use std::fs;
use std::path::Path;
use std::process::Command;

// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    println!("cargo:rerun-if-changed=shared/src/settings/schema.rs");
    for project in JS_PROJECTS {
        build_js_assets(project);
    }

    let schema_dest_path = get_cargo_target_dir().unwrap().join("settings.schema.json");

    let schema = schema_for!(Settings);

    fs::write(
        schema_dest_path,
        serde_json::to_string_pretty(&schema).unwrap(),
    )
    .unwrap();
}

/// A TypeScript project that is built with bun into JS assets embedded via
/// `include_str!`.
struct JsProject {
    /// Directory (relative to the shared crate root) containing package.json.
    dir: &'static str,
    /// Generated bundles (relative to the shared crate root).
    outputs: &'static [&'static str],
}

// `src` is included as an input directory; individual files are appended in
// `build_js_assets` so that added/removed sources are tracked.
const JS_PROJECTS: &[JsProject] = &[
    JsProject {
        dir: "src/source/lnreader/lnreader_js",
        outputs: &["src/source/lnreader/assets/libs.js"],
    },
    JsProject {
        dir: "src/source/mangayomi/polyfill",
        outputs: &["src/source/mangayomi/js_assets/polyfill.js"],
    },
];

// Regenerates the JS bundles from the TypeScript sources when any source or
// manifest file is newer than the generated output. Requires bun; the
// committed bundles keep builds working without it.
fn build_js_assets(project: &JsProject) {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let js_dir = root.join(project.dir);
    let mut inputs: Vec<String> = vec![
        format!("{}/package.json", project.dir),
        format!("{}/bun.lock", project.dir),
        format!("{}/tsconfig.json", project.dir),
        format!("{}/src", project.dir),
    ];
    if let Ok(entries) = fs::read_dir(js_dir.join("src")) {
        for entry in entries.flatten() {
            if entry.file_type().is_ok_and(|t| t.is_file()) {
                inputs.push(format!(
                    "{}/src/{}",
                    project.dir,
                    entry.file_name().to_string_lossy()
                ));
            }
        }
    }
    for input in &inputs {
        println!("cargo:rerun-if-changed={input}");
    }
    let out_mtime = project
        .outputs
        .iter()
        .map(|out| fs::metadata(root.join(out)).and_then(|m| m.modified()))
        .collect::<Result<Vec<_>, _>>()
        .unwrap_or_default()
        .into_iter()
        .min()
        .unwrap_or(std::time::SystemTime::UNIX_EPOCH);
    let stale = inputs.iter().any(|p| {
        let m = match fs::metadata(root.join(p)).and_then(|m| m.modified()) {
            Ok(m) => m,
            Err(_) => return true,
        };
        m.cmp(&out_mtime).is_gt()
    });
    if !stale {
        return;
    }
    if Command::new("bun")
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .status()
        .is_err()
    {
        panic!(
            "{} JS bundle is missing or out of date and bun is not installed; \
             run `bash scripts/build-js-assets.sh` to regenerate it",
            project.dir
        );
    }
    let status = Command::new("bun")
        .current_dir(&js_dir)
        .args(["install"])
        .status()
        .expect("failed to run bun install");
    assert!(status.success(), "bun install failed");
    let status = Command::new("bun")
        .current_dir(&js_dir)
        .args(["run", "build"])
        .status()
        .expect("failed to run bun build");
    assert!(status.success(), "bun build failed");
}

fn get_cargo_target_dir() -> Result<std::path::PathBuf, Box<dyn std::error::Error>> {
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR")?);
    let profile = std::env::var("PROFILE")?;
    let mut target_dir = None;
    let mut sub_path = out_dir.as_path();
    while let Some(parent) = sub_path.parent() {
        if parent.ends_with(&profile) {
            target_dir = Some(parent);
            break;
        }
        sub_path = parent;
    }
    let target_dir = target_dir.ok_or("not found")?;
    Ok(target_dir.to_path_buf())
}
